/** Deutsche Städte (kreisfrei und größere Kreisstädte) plus gängige Ortsangaben. */
const STADT_EXTRAS = [
  'außerhalb Berlin',
  'Brandenburg',
  'Bayern',
  'Baden-Württemberg'
];

const DEUTSCHE_STAEDTE = [
  'Aachen',
  'Aalen',
  'Ahlen',
  'Albstadt',
  'Alsdorf',
  'Altenburg',
  'Amberg',
  'Andernach',
  'Ansbach',
  'Arnsberg',
  'Aschaffenburg',
  'Augsburg',
  'Aurich',
  'Backnang',
  'Bad Homburg vor der Höhe',
  'Bad Kreuznach',
  'Bad Oeynhausen',
  'Bad Salzuflen',
  'Baden-Baden',
  'Bamberg',
  'Bautzen',
  'Bayreuth',
  'Beckum',
  'Bensheim',
  'Bergheim',
  'Bergisch Gladbach',
  'Bergkamen',
  'Berlin',
  'Bielefeld',
  'Bietigheim-Bissingen',
  'Bocholt',
  'Bochum',
  'Bonn',
  'Borken',
  'Bottrop',
  'Brandenburg an der Havel',
  'Braunschweig',
  'Bremen',
  'Bremerhaven',
  'Brühl',
  'Buchholz in der Nordheide',
  'Bünde',
  'Burgdorf',
  'Castrop-Rauxel',
  'Celle',
  'Chemnitz',
  'Cloppenburg',
  'Coburg',
  'Coesfeld',
  'Cottbus',
  'Cuxhaven',
  'Dachau',
  'Darmstadt',
  'Datteln',
  'Delmenhorst',
  'Dessau-Roßlau',
  'Detmold',
  'Dietzenbach',
  'Dinslaken',
  'Dormagen',
  'Dorsten',
  'Dortmund',
  'Dresden',
  'Duisburg',
  'Dülmen',
  'Düren',
  'Düsseldorf',
  'Eisenach',
  'Elmshorn',
  'Emden',
  'Erftstadt',
  'Erfurt',
  'Erlangen',
  'Eschweiler',
  'Essen',
  'Esslingen am Neckar',
  'Euskirchen',
  'Filderstadt',
  'Flensburg',
  'Forchheim',
  'Frankenthal (Pfalz)',
  'Frankfurt (Oder)',
  'Frankfurt am Main',
  'Frechen',
  'Freiberg',
  'Freiburg im Breisgau',
  'Freising',
  'Freital',
  'Friedrichshafen',
  'Fulda',
  'Fürth',
  'Garbsen',
  'Gelsenkirchen',
  'Gera',
  'Gießen',
  'Gifhorn',
  'Gladbeck',
  'Goch',
  'Göppingen',
  'Görlitz',
  'Goslar',
  'Göttingen',
  'Greifswald',
  'Grevenbroich',
  'Gronau (Westf.)',
  'Gummersbach',
  'Gütersloh',
  'Hagen',
  'Halle (Saale)',
  'Hamburg',
  'Hameln',
  'Hamm',
  'Hanau',
  'Hannover',
  'Hattingen',
  'Heidelberg',
  'Heidenheim an der Brenz',
  'Heilbronn',
  'Hemer',
  'Hennef (Sieg)',
  'Herford',
  'Herne',
  'Herten',
  'Hilden',
  'Hildesheim',
  'Hof',
  'Homburg',
  'Hürth',
  'Ibbenbüren',
  'Idar-Oberstein',
  'Ingolstadt',
  'Iserlohn',
  'Isernhagen',
  'Jena',
  'Kaiserslautern',
  'Kamen',
  'Kamp-Lintfort',
  'Karlsruhe',
  'Kassel',
  'Kaufbeuren',
  'Kehl',
  'Kelkheim (Taunus)',
  'Kempten (Allgäu)',
  'Kerpen',
  'Kiel',
  'Kirchheim unter Teck',
  'Kleve',
  'Koblenz',
  'Köln',
  'Konstanz',
  'Krefeld',
  'Kreuztal',
  'Kulmbach',
  'Laatzen',
  'Lahr/Schwarzwald',
  'Lampertheim',
  'Landau in der Pfalz',
  'Landsberg am Lech',
  'Landshut',
  'Langen (Hessen)',
  'Langenfeld (Rheinland)',
  'Langenhagen',
  'Leer (Ostfriesland)',
  'Lehrte',
  'Leichlingen (Rheinland)',
  'Leimen',
  'Leinfelden-Echterdingen',
  'Leipzig',
  'Lemgo',
  'Lengerich',
  'Leonberg',
  'Leutkirch im Allgäu',
  'Leverkusen',
  'Lippstadt',
  'Lörrach',
  'Lübbecke',
  'Lübeck',
  'Lüdenscheid',
  'Ludwigsburg',
  'Ludwigshafen am Rhein',
  'Lüneburg',
  'Lünen',
  'Magdeburg',
  'Maintal',
  'Mainz',
  'Mannheim',
  'Marburg',
  'Marl',
  'Mechernich',
  'Meerbusch',
  'Meißen',
  'Melle',
  'Memmingen',
  'Menden (Sauerland)',
  'Meppen',
  'Merseburg',
  'Meschede',
  'Mettmann',
  'Minden',
  'Moers',
  'Mönchengladbach',
  'Monheim am Rhein',
  'Mosbach',
  'Mühlhausen/Thüringen',
  'Mülheim an der Ruhr',
  'München',
  'Münster',
  'Nagold',
  'Nettetal',
  'Neu-Isenburg',
  'Neu-Ulm',
  'Neubrandenburg',
  'Neumünster',
  'Neunkirchen',
  'Neuruppin',
  'Neuss',
  'Neustadt am Rübenberge',
  'Neustadt an der Weinstraße',
  'Neuwied',
  'Nienburg/Weser',
  'Norderstedt',
  'Nordhorn',
  'Nürnberg',
  'Nürtingen',
  'Oberhausen',
  'Oberursel (Taunus)',
  'Offenbach am Main',
  'Offenburg',
  'Oldenburg',
  'Oranienburg',
  'Osnabrück',
  'Osterholz-Scharmbeck',
  'Overath',
  'Paderborn',
  'Papenburg',
  'Passau',
  'Peine',
  'Pforzheim',
  'Pinneberg',
  'Pirmasens',
  'Pirna',
  'Plauen',
  'Potsdam',
  'Pulheim',
  'Radebeul',
  'Rastatt',
  'Ratingen',
  'Ravensburg',
  'Recklinghausen',
  'Regensburg',
  'Remscheid',
  'Rendsburg',
  'Reutlingen',
  'Rheda-Wiedenbrück',
  'Rheine',
  'Riesa',
  'Rodgau',
  'Rosenheim',
  'Rostock',
  'Rottenburg am Neckar',
  'Rottweil',
  'Saarbrücken',
  'Saarlouis',
  'Salzgitter',
  'Sankt Augustin',
  'Schwabach',
  'Schwäbisch Gmünd',
  'Schwäbisch Hall',
  'Schwandorf',
  'Schweinfurt',
  'Schwerin',
  'Schwerte',
  'Schwetzingen',
  'Seelze',
  'Seevetal',
  'Siegburg',
  'Siegen',
  'Sindelfingen',
  'Singen (Hohentwiel)',
  'Soest',
  'Solingen',
  'Speyer',
  'Spremberg',
  'Stade',
  'Stolberg (Rheinland)',
  'Stralsund',
  'Straubing',
  'Stuttgart',
  'Suhl',
  'Sundern (Sauerland)',
  'Trier',
  'Troisdorf',
  'Tübingen',
  'Tuttlingen',
  'Übach-Palenberg',
  'Uelzen',
  'Ulm',
  'Unna',
  'Unterschleißheim',
  'Vechta',
  'Velbert',
  'Viersen',
  'Villingen-Schwenningen',
  'Waiblingen',
  'Waldkraiburg',
  'Waltrop',
  'Warburg',
  'Wedel',
  'Weiden in der Oberpfalz',
  'Weil am Rhein',
  'Weimar',
  'Weinheim',
  'Weinstadt',
  'Weißenfels',
  'Wermelskirchen',
  'Wernigerode',
  'Wesel',
  'Wesseling',
  'Wetzlar',
  'Wiesbaden',
  'Wilhelmshaven',
  'Willich',
  'Witten',
  'Wolfenbüttel',
  'Wolfsburg',
  'Worms',
  'Wuppertal',
  'Würzburg',
  'Zittau',
  'Zweibrücken',
  'Zwickau'
];

function uniqueSorted(values) {
  const seen = new Set();
  const out = [];
  for (const raw of values) {
    const v = String(raw || '').trim();
    if (!v) continue;
    const key = v.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(v);
  }
  return out;
}

export const LEAD_STADT_OPTIONS = uniqueSorted([...STADT_EXTRAS, ...DEUTSCHE_STAEDTE]);

export function filterStadtOptions(query, limit = 40) {
  const q = String(query || '').trim().toLowerCase();
  const list = LEAD_STADT_OPTIONS;
  if (!q) return list.slice(0, limit);
  return list.filter((stadt) => stadt.toLowerCase().includes(q)).slice(0, limit);
}

export function isKnownStadt(value) {
  const v = String(value || '').trim().toLowerCase();
  if (!v) return false;
  return LEAD_STADT_OPTIONS.some((stadt) => stadt.toLowerCase() === v);
}
